[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#bac2de"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.selection]
text = "#cdd6f4"
background = "#45475a"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#cdd6f4"
background = "#181825"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#cdd6f4"
background = "#585b70"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#a6adc8"

[colors.dim]
black   = "#313244"
red     = "#e78284"
green   = "#8ec07c"
yellow  = "#e5c890"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#88c0d0"
white   = "#7f849c"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 1.0
decorations = "Full"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11.0

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
